### ISSUE TITLE
Ability to disable logging

### ISSUE THREAD

**Issue by toddkazakov** [lonelyplanet/travel-agent#34]
Moreover, in OP we need conform to the logstash format to make sure logs are properly ingested by fluentd.

Bunyan doesn't support changing the format of the log entries and logs either useless (like `pid` which doesn't make sense in the context of docker) or badly named parameters (why not `error` seems better than `err`). 

My proposal is to add the ability to disable logging until we agree on a common format. 

@jcreamer898 what do you think?

**Comment by jcreamer898** [comment]
Bunyan is what we have always used. It isn't working? That's news to me. :)

**Comment by toddkazakov** [comment]
My point here is that apps should be the one responsible for specifying the logger and the log format. Bunyan clearly doesn't support this. I'd like to at least have the option to disable it. Not being able to specify meaningful log level in the message (what does `"level": 30` even mean?) makes it pretty difficult to work with.

**Comment by jcreamer898** [comment]
Ok, cool, I agree.
