### ISSUE TITLE
Thoughts on using Webpack's new API for loader options?

### ISSUE THREAD

**Issue by thomasthesecond** [lonelyplanet/travel-agent#7]
Since Webpack 2, you can use an object to define a loader's options. I think this is easier to read than the older `query` API. https://webpack.js.org/guides/migrating/#what-are-options-

For example, [this code](https://github.com/lonelyplanet/travel-agent/blob/master/packages/travel-agent-server/src/webpack/loaders.ts):

```js
{
  loader: "typings-for-css-modules-loader?namedExport&modules&localIdentName=[name]__[local]___[hash:base64:5]",
}
```

could be rewritten as:

```js
{
  loader: "typings-for-css-modules-loader",
  options: {
    namedExport: true,
    modules: true,
    localIdentName: "[name]__[local]___[hash:base64:5]",
  },
}
```

What do you think? @jcreamer898

**Comment by jcreamer898** [comment]
Thanks for this, will fix that now.
